app = "frontend-lively-hill-6164"
primary_region = "fra"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["https://github.com/heroku/buildpack-static"]

[[statics]]
  guest_path = "/app/dist"
  url_prefix = "/"
