app = "frontend-lively-hill-6164"
primary_region = "fra"

[[statics]]
  guest_path = "dist"
  url_prefix = "/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
